Add ETCD_IMAGE_TAG option required for etcd-member.service
vmware/ansible-etcd-cluster pull request #2
Opened 2017-07-25 05:59 UTC by puneetkatyal

2017-07-25 11:29 UTC, naveens approved these changes

2017-08-08 21:51 UTC, imkin requested changes

2017-08-08 21:51 UTC, imkin commented on defaults/main.yml
> +etcd_image_tag: "v3.1.0"
Where is the etcd image?

2017-08-08 21:52 UTC, imkin commented
Can you add description to this. It is usually pulled from the commit message. 

How will this branching work between current 1.4 and 1.7 features.

2017-08-11 19:06 UTC, puneetkatyal commented on defaults/main.yml
> +etcd_image_tag: "v3.1.0"
https://coreos.com/etcd/docs/latest/getting-started-with-etcd.html#setting-up-etcd
> Container Linux's etcd-member.service systemd unit knows how to fetch and run the current etcd v3.x container image, providing etcd v3 without requiring the binary to be present in every default OS installation.

2017-08-11 19:29 UTC, puneetkatyal commented
Updated commit description and add change to fix proxy mode (a.k.a. 'gateway') for etcd3

2017-08-11 21:29 UTC, imkin commented on defaults/main.yml
> +etcd_image_tag: "v3.1.0"
I meant the location of etcd image. If it is pulled from coreos the setup might have issues like we have with existing images taking a lot of time to download.

2017-08-14 15:39 UTC, puneetkatyal commented on defaults/main.yml
> +etcd_image_tag: "v3.1.0"
Its's downloaded from quoy.io by default. I've added an option to update ETCD_IMAGE_URL to a different source.

2017-08-14 16:00 UTC, imkin approved these changes

2017-08-14 18:47 UTC, merged